Repository googleapis/java-texttospeech, pull requests merged in 2020-09, with the labels that each got.

#218 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/release/stage.cfg
  synth.metadata
Labels: api: texttospeech, cla: yes, context: full

#225 chore: regenerate README
  README.md
  synth.metadata
Labels: api: texttospeech, cla: yes, context: none

#228 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#239 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#240 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#241 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: texttospeech, automerge, cla: yes

#246 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#248 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
