Repository googleapis/java-texttospeech, pull requests merged in 2020-11, with the labels that each got.

#284 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, automerge, cla: yes

#291 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#289 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, cla: yes

#293 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, automerge, cla: yes

#295 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#294 chore: added missing region tag in pom.xml
  samples/snippets/pom.xml
Labels: api: texttospeech, cla: yes

#302 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#305 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#307 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, cla: yes

#309 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, automerge, cla: yes

#310 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, automerge, cla: yes

#311 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#312 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full, samples
