Repository googleapis/java-texttospeech, pull requests merged in 2020-08, with the labels that each got.

#203 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#205 docs: escape `*` characters in comments
  README.md
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/TextToSpeechClient.java
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/TextToSpeechClient.java
  proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/ListVoicesRequest.java
  proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/ListVoicesRequestOrBuilder.java
  proto-google-cloud-texttospeech-v1/src/main/proto/google/cloud/texttospeech/v1/cloud_tts.proto
  proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/ListVoicesRequest.java
  proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/ListVoicesRequestOrBuilder.java
  proto-google-cloud-texttospeech-v1beta1/src/main/proto/google/cloud/texttospeech/v1beta1/cloud_tts.proto
  synth.metadata
Labels: cla: yes, context: partial

#209 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#211 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#201 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /texttospeech/beta
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/texttospeech/ListAllSupportedVoicesBeta.java
  samples/snippets/src/main/java/com/example/texttospeech/QuickstartSampleBeta.java
  samples/snippets/src/main/java/com/example/texttospeech/SynthesizeFileBeta.java
  samples/snippets/src/main/java/com/example/texttospeech/SynthesizeTextBeta.java
  samples/snippets/src/test/java/com/example/texttospeech/ListAllSupportedVoicesBetaIT.java
  samples/snippets/src/test/java/com/example/texttospeech/SynthesizeFileBetaIT.java
  samples/snippets/src/test/java/com/example/texttospeech/SynthesizeTextBetaIT.java
Labels: cla: yes

#216 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  samples/snippets/src/main/java/com/example/texttospeech/SynthesizeTextBeta.java
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: partial
