Repository googleapis/java-texttospeech, pull requests merged in 2021-08, with the labels that each got.

#510 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: texttospeech, automerge, context: full

#515 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: texttospeech, automerge

#513 feat!: release gapic-generator-java v2.0.0
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/TextToSpeechSettings.java
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/stub/GrpcTextToSpeechStub.java
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/stub/TextToSpeechStubSettings.java
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/TextToSpeechSettings.java
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/stub/GrpcTextToSpeechStub.java
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/stub/TextToSpeechStubSettings.java
  synth.metadata
Labels: cla: yes, api: texttospeech, automerge, context: full

#523 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: texttospeech, automerge, context: full

#525 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: texttospeech, automerge

#526 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: texttospeech, automerge

#529 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: texttospeech, automerge

#536 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: texttospeech, automerge

#535 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: texttospeech, automerge

#527 chore: update gapic-generator-java version to 2.1.0
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/stub/TextToSpeechStubSettings.java
  google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/stub/TextToSpeechStubSettings.java
  synth.metadata
Labels: kokoro:force-run, cla: yes, api: texttospeech, automerge, context: full

#543 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: texttospeech, automerge
