Repository googleapis/java-texttospeech, pull requests merged in 2021-05, with the labels that each got.

#444 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: none

#445 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: texttospeech, automerge, cla: yes

#455 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, automerge, cla: yes

#456 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#457 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, automerge, cla: yes

#459 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, automerge, cla: yes

#460 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#462 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#465 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#470 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: texttospeech, automerge, cla: yes

#468 fix: Fix the last element of the C# namespace to V1Beta1 instead of V1beta1
  proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/TextToSpeechProto.java
  proto-google-cloud-texttospeech-v1beta1/src/main/proto/google/cloud/texttospeech/v1beta1/cloud_tts.proto
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full
